### ISSUE TITLE
nrfx_qspi - nrfx_qspi_lfm_start/xfer handler mode bug

### ISSUE THREAD

**Issue by andenoremode** [NordicSemiconductor/nrfx#86] opened 2021-04-21 12:15 UTC
The nrfx_qspi_cinstr_xfer() function disables the ready interrupt so that the qspi_ready_wait() can poll the event status.

nrfx_qspi_lfm_start/()xfer() functions does not do this. So when handler mode is used, the interrupt will trigger and clear the event, causing qspi_ready_wait() to return NRFX_ERROR_TIMEOUT.

**Comment by nika-nordic** [comment] 2021-05-10 07:38
Hi @andenoremode, thank you for your comment. I will check the issue internally

**Comment by nika-nordic** [comment] 2021-06-11 13:18
Just FYI - we identified the issue and got someone working on it

**Comment by nika-nordic** [comment] 2021-06-22 10:41
Hi, the issue is fixed on our internal development branch - it will be present in next nrfx release

**Comment by nika-nordic** [comment] 2021-11-24 11:19
Fixed in nrfx 2.6.0

**Closed by nika-nordic** 2021-11-24 11:19 UTC
